---
apiVersion: v1
kind: List
items:
- apiVersion: capabilities.3scale.net/v1beta1
  kind: Product
  metadata:
    annotations:
      3scale_toolbox_created_at: '2023-03-22T10:07:57Z'
      3scale_toolbox_version: 0.20.0
    name: oidc.api.etwqkmov
  spec:
    name: OIDC API (1.1)
    systemName: oidc_api_1_1
    description: Demo OIDC protection for PoC purposes
    mappingRules:
    - httpMethod: GET
      pattern: "/common/security/v3/oauth20/authorize"
      metricMethodRef: getAuthorize
      increment: 1
      last: false
    - httpMethod: POST
      pattern: "/uyg-v3/v3/login"
      metricMethodRef: postLogin
      increment: 1
      last: false
    - httpMethod: GET
      pattern: "/uyg-v3/v3/login"
      metricMethodRef: getLogin
      increment: 1
      last: false
    - httpMethod: POST
      pattern: "/uyg-v3/v3/username"
      metricMethodRef: postUsername
      increment: 1
      last: false
    - httpMethod: GET
      pattern: "/uyg-v3/v3/username"
      metricMethodRef: getUsername
      increment: 1
      last: false
    - httpMethod: POST
      pattern: "/authentication/tms/v3"
      metricMethodRef: postTMS
      increment: 1
      last: false
    - httpMethod: GET
      pattern: "/authentication/tms/v3"
      metricMethodRef: getTMS
      increment: 1
      last: false
    - httpMethod: GET
      pattern: "/uyg-v3/assets"
      metricMethodRef: getAssets
      increment: 1
      last: false
    - httpMethod: POST
      pattern: "/authentication/tcs/v3"
      metricMethodRef: postTCS
      increment: 1
      last: false
    - httpMethod: GET
      pattern: "/authentication/tcs/v3"
      metricMethodRef: getTCS
      increment: 1
      last: false
    metrics:
      hits:
        friendlyName: Hits
        unit: hit
        description: Number of API hits
    methods:
      getTCS:
        friendlyName: getTCS
        description: ''
      postTCS:
        friendlyName: postTCS
        description: ''
      getAssets:
        friendlyName: getAssests
        description: ''
      getTMS:
        friendlyName: getTMS
        description: ''
      postTMS:
        friendlyName: postTMS
        description: ''
      getUsername:
        friendlyName: getUsername
        description: ''
      postUsername:
        friendlyName: postUsername
        description: ''
      getLogin:
        friendlyName: getLogin
        description: ''
      postLogin:
        friendlyName: postLogin
        description: ''
      getAuthorize:
        friendlyName: getAuthorize
        description: ''
    policies:
    - name: default_credentials
      version: builtin
      configuration:
        auth_type: user_key
        user_key: 802e2ccd4008b006e7272aef941750da
      enabled: true
    - name: apicast
      version: builtin
      configuration: {}
      enabled: true
    - name: custom-headers-modification
      version: '0.1'
      configuration:
        request:
        - value_type: plain
          verb: GET
          header: location
          op: set
          path: "/common/security/v3/oauth20/authorize"
          value: https://apigw.apps.fw.garanti.com.tr/uyg-v3/v3/login
        - value_type: plain
          op: updateCookie
          header: PD-S-SESSION-ID
          verb: GET
          path: "/common/security/v3/oauth20/authorize"
        - value_type: plain
          op: updateCookie
          path: "/uyg-v3/v3/username"
          verb: GETPOST
          header: PD-S-SESSION-ID
        - value_type: plain
          op: substitution
          path: "/uyg-v3/v3/username"
          verb: GETPOST
          header: location
          value: https://ark-sso.fw.garanti.com.tr/mga-v3/sps/oauth/oauth20/authorize-https://apigw.apps.fw.garanti.com.tr/common/security/v3/oauth20/authorize
      enabled: true
    - name: conditional
      version: builtin
      configuration:
        condition:
          combine_op: and
          operations:
          - right_type: plain
            left_type: liquid
            left: "{{headers['location']}}"
            op: "!="
            right: https://ark-sso.fw.garanti.com.tr/uyg-v3/v3/login?error
          - right_type: plain
            left_type: liquid
            left: "{{http_method}}"
            op: "=="
            right: POST
        policy_chain:
        - name: custom-headers-modification
          version: '0.1'
          configuration:
            request:
            - value_type: plain
              op: set
              path: "/uyg-v3/v3/login"
              verb: POST
              header: location
              value: https://apigw.apps.fw.garanti.com.tr/uyg-v3/v3/username
          enabled: true
      enabled: true
    - name: conditional
      version: builtin
      configuration:
        condition:
          combine_op: and
          operations:
          - right_type: plain
            left_type: liquid
            left: "{{headers['location']}}"
            op: "=="
            right: https://ark-sso.fw.garanti.com.tr/uyg-v3/v3/login?error
          - right_type: plain
            left_type: liquid
            left: "{{http_method}}"
            op: "=="
            right: POST
        policy_chain:
        - name: custom-headers-modification
          version: '0.1'
          configuration:
            request:
            - value_type: plain
              op: set
              path: "/uyg-v3/v3/login"
              verb: POST
              header: location
              value: https://apigw.apps.fw.garanti.com.tr/uyg-v3/v3/errorPage
            - value_type: plain
              op: newCookie
              path: "/uyg-v3/v3/login"
              verb: POST
              header: locationIsam
              value: https://ark-sso.fw.garanti.com.tr/uyg-v3/v3/login?error
          enabled: true
      enabled: true
    applicationPlans:
      sandbox:
        name: Sandbox
        appsRequireApproval: false
        trialPeriod: 0
        setupFee: 0.0
        custom: false
        state: published
        costMonth: 0.0
        pricingRules: []
        limits:
        - period: minute
          value: 2
          metricMethodRef:
            systemName: hits
      production:
        name: Production
        appsRequireApproval: false
        trialPeriod: 0
        setupFee: 0.0
        custom: false
        state: published
        costMonth: 0.0
        pricingRules: []
        limits: []
    backendUsages:
      tcsbackend:
        path: "/authentication"
      authorizeg:
        path: "/common/security/v3/oauth20/authorize"
      uyg-v3-backend:
        path: "/uyg-v3"
    deployment:
      apicastHosted:
        authentication:
          userkey:
            authUserKey: user_key
            credentials: query
            security:
              hostHeader:
              secretToken: Shared_secret_sent_from_proxy_to_API_backend_3b6589521d78a0fa
            gatewayResponse:
              errorStatusAuthFailed: 403
              errorHeadersAuthFailed: text/plain; charset=us-ascii
              errorAuthFailed: Authentication failed
              errorStatusAuthMissing: 403
              errorHeadersAuthMissing: text/plain; charset=us-ascii
              errorAuthMissing: Authentication parameters missing
              errorStatusNoMatch: 404
              errorHeadersNoMatch: text/plain; charset=us-ascii
              errorNoMatch: No Mapping Rule matched
              errorStatusLimitsExceeded: 429
              errorHeadersLimitsExceeded: text/plain; charset=us-ascii
              errorLimitsExceeded: Usage limit exceeded
- apiVersion: capabilities.3scale.net/v1beta1
  kind: Backend
  metadata:
    annotations:
      3scale_toolbox_created_at: '2023-03-22T10:08:00Z'
      3scale_toolbox_version: 0.20.0
    name: tcsbackend.bvxjudmq
  spec:
    name: AuthenticationG backend
    systemName: tcsbackend
    privateBaseURL: https://echo-api.apps.ocp4.quitala.eu:443/authentication
    description: ''
    mappingRules:
    - httpMethod: GET
      pattern: "/"
      metricMethodRef: hits
      increment: 1
      last: false
    metrics:
      hits:
        friendlyName: Hits
        unit: hit
        description: Number of API hits
    methods: {}
- apiVersion: capabilities.3scale.net/v1beta1
  kind: Backend
  metadata:
    annotations:
      3scale_toolbox_created_at: '2023-03-22T10:08:00Z'
      3scale_toolbox_version: 0.20.0
    name: authorizeg.osweqkcp
  spec:
    name: AuthorizeGBackend
    systemName: authorizeg
    privateBaseURL: https://echo-api.apps.ocp4.quitala.eu:443/mga-v3/sps/oauth/oauth20/authorize
    description: ''
    mappingRules: []
    metrics:
      hits:
        friendlyName: Hits
        unit: hit
        description: Number of API hits
    methods: {}
- apiVersion: capabilities.3scale.net/v1beta1
  kind: Backend
  metadata:
    annotations:
      3scale_toolbox_created_at: '2023-03-22T10:08:01Z'
      3scale_toolbox_version: 0.20.0
    name: uyg-v3-backend.xzrdkgme
  spec:
    name: uyg-v3-backend
    systemName: uyg-v3-backend
    privateBaseURL: https://echo-api.apps.ocp4.quitala.eu:443/uyg-v3
    description: uyg-v3-backend
    mappingRules: []
    metrics:
      hits:
        friendlyName: Hits
        unit: hit
        description: Number of API hits
    methods: {}
